import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const enableOrchids = process.env.NEXT_PUBLIC_ORCHIDS === "1";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Script id="localstorage-guard" strategy="beforeInteractive">{`
          (function () {
            try {
              var ls = window.localStorage;
              if (!ls || typeof ls.getItem !== "function") {
                var store = {};
                window.localStorage = {
                  getItem: function (k) { return Object.prototype.hasOwnProperty.call(store, k) ? store[k] : null; },
                  setItem: function (k, v) { store[k] = String(v); },
                  removeItem: function (k) { delete store[k]; },
                  clear: function () { store = {}; },
                  key: function (i) { return Object.keys(store)[i] || null; },
                  get length() { return Object.keys(store).length; }
                };
              }
            } catch (e) {
              // If access to localStorage is blocked, ignore to avoid hard crash
            }
          })();
        `}</Script>
        {enableOrchids && (
          <>
            <Script
              id="orchids-browser-logs"
              src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts/orchids-browser-logs.js"
              strategy="afterInteractive"
              data-orchids-project-id="4dff7514-95f7-46fb-9f4d-e52f6d29338b"
            />
            <ErrorReporter />
            <Script
              src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
              strategy="afterInteractive"
              data-target-origin="*"
              data-message-type="ROUTE_CHANGE"
              data-include-search-params="true"
              data-only-in-iframe="true"
              data-debug="true"
              data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
            />
          </>
        )}
        {children}
        {enableOrchids && <VisualEditsMessenger />}
      </body>
    </html>
  );
}
